config/routes.rb
Bioduino::Application.routes.draw do
  resources :datapoints


  resources :experiments
  match "/current" => "experiments#current"
  match "/experiments/raw_data/:id" => "experiments#raw_data", :as => :raw_data
  root :to => "home#index"

end

app/models/datapoint.rb
class Datapoint < ActiveRecord::Base
  attr_accessible :value, :error, :dataType, :time, :group_int
  has_one :experiment
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  attr_accessible :startTime
  has_many :datapoints

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/datapoints_controller.rb
class DatapointsController < ApplicationController
  # GET /datapoints
  # GET /datapoints.json
  def index
    @datapoints = Datapoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datapoints }
    end
  end

  # GET /datapoints/1
  # GET /datapoints/1.json
  def show
    @datapoint = Datapoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datapoint }
    end
  end

  # GET /datapoints/new
  # GET /datapoints/new.json
  def new
    @datapoint = Datapoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datapoint }
    end
  end

  # GET /datapoints/1/edit
  def edit
    @datapoint = Datapoint.find(params[:id])
  end

  # POST /datapoints
  # POST /datapoints.json
  def create
    @datapoint = Datapoint.new(params[:datapoint])

    respond_to do |format|
      if @datapoint.save
        format.html { redirect_to @datapoint, notice: 'Datapoint was successfully created.' }
        format.json { render json: @datapoint, status: :created, location: @datapoint }
      else
        format.html { render action: "new" }
        format.json { render json: @datapoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /datapoints/1
  # PUT /datapoints/1.json
  def update
    @datapoint = Datapoint.find(params[:id])

    respond_to do |format|
      if @datapoint.update_attributes(params[:datapoint])
        format.html { redirect_to @datapoint, notice: 'Datapoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datapoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datapoints/1
  # DELETE /datapoints/1.json
  def destroy
    @datapoint = Datapoint.find(params[:id])
    @datapoint.destroy

    respond_to do |format|
      format.html { redirect_to datapoints_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.order("id desc").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @experiment = Experiment.find(params[:id])
    @temperatures = @experiment.datapoints.where(:dataType => "temperature").order("id desc").first(70000)
    @pHs = @experiment.datapoints.where(:dataType => "pH").order("id desc").first(70000)
    @agitations = @experiment.datapoints.where(:dataType => "agitation").order("id desc").first(70000)
    @dissolvedOxygens = @experiment.datapoints.where(:dataType => "do").order("id desc").first(70000)
    gon.temperatureData = [{:values => @temperatures.map{ |d| {:x => (d.time-@experiment.startTime).seconds, :y => d.value} }, :key=> "Experiment id:#{@experiment.id}", :color =>'#ff7f0e'}]
    gon.pHData = [{:values => @pHs.map{ |d| {:x => (d.time-@experiment.startTime).seconds, :y => d.value} }, :key=> "Experiment id:#{@experiment.id}", :color =>'#ff7f0e'}]
    gon.doData = [{:values => @dissolvedOxygens.map{ |d| {:x => (d.time-@experiment.startTime).seconds, :y => d.value} }, :key=> "Experiment id:#{@experiment.id}", :color =>'#ff7f0e'}]
    gon.agitData = [{:values => @agitations.map{ |d| {:x => (d.time-@experiment.startTime).seconds, :y => d.value} }, :key=> "Experiment id:#{@experiment.id}", :color =>'#ff7f0e'}]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experiment }
    end
  end



  # GET /experiments/new
  # GET /experiments/new.json
  def new
    @experiment = Experiment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end

  def current
    @experiment = Experiment.last
    redirect_to @experiment
  end

  def raw_data
    @experiment = Experiment.find(params[:id])
    @temperatures = @experiment.datapoints.where(:dataType => "temperature").order("id desc").all
    @pHs = @experiment.datapoints.where(:dataType => "pH").order("id desc").all
    @agitations = @experiment.datapoints.where(:dataType => "agitation").order("id desc").all
    @dissolvedOxygens = @experiment.datapoints.where(:dataType => "do").order("id desc").all
    @maximumGroupInt = @experiment.datapoints.maximum("group_int")
    @minimumGroupInt = @experiment.datapoints.minimum("group_int")
    respond_to do |format|
      format.html
      format.xls 
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datapoints_helper.rb
module DatapointsHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/datapoints/_form.html.erb
<%= form_for(@datapoint) do |f| %>
  <% if @datapoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datapoint.errors.count, "error") %> prohibited this datapoint from being saved:</h2>

      <ul>
      <% @datapoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datapoints/edit.html.erb
<h1>Editing datapoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @datapoint %> |
<%= link_to 'Back', datapoints_path %>

app/views/datapoints/index.html.erb
<h1>Listing datapoints</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @datapoints.each do |datapoint| %>
  <tr>
    <td><%= link_to 'Show', datapoint %></td>
    <td><%= link_to 'Edit', edit_datapoint_path(datapoint) %></td>
    <td><%= link_to 'Destroy', datapoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Datapoint', new_datapoint_path %>

app/views/datapoints/new.html.erb
<h1>New datapoint</h1>

<%= render 'form' %>

<%= link_to 'Back', datapoints_path %>

app/views/datapoints/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_datapoint_path(@datapoint) %> |
<%= link_to 'Back', datapoints_path %>

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<h1>Listing experiments</h1>

<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>id</th>
    <th>Start Time</th>
    <th>Datapoints</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @experiments.each do |experiment| %>
	<% if !experiment.datapoints.empty? %>
	  <tr>
	    <td><%= experiment.id %></td>
	    <td><%= experiment.startTime %></td>
	    <td><%= experiment.datapoints.count %></td>
	    <td><%= button_to "Show", experiment, {:method => :get }%> </td>
	    <td><%= button_to "Raw Data", raw_data_path(experiment) %></td>
	    <td><%= button_to "Excel", raw_data_path(experiment, format: "xls")%></td>
	  </tr>
	 <% end %>
<% end %>
</table>

<br />

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/raw_data.html.erb
<p id="notice"><%= notice %></p>
<style>
 	.button_to {
 		display:inline-block;
 	}
</style>

<div class="row">
	<div class="span3">
		<div class ="affix">
			<div class="raw_links">
		<%= link_to "Graphs", @experiment, :class=>"btn" %> 
			<%= link_to "Excel", raw_data_path(@experiment, format: "xls"), :class => "btn"%> 
			</div>
			<h4>Jump to:</h4>
			<ul class="nav nav-pills nav-stacked ">
				<li><%= link_to "Temperature", "#raw_temp", :class =>"btn" %></li>
				<li><%= link_to "pH", "#raw_ph", :class => "btn" %></li>
				<li><%= link_to "DO", "#raw_do", :class => "btn" %></li>
				<li><%= link_to "Agitations", "#raw_agit", :class => "btn" %></li>
			</ul>
			<script>
			$('#navbar').affix()
			</script>
		</div>
	</div>
	<div class="span9">
		<div id="raw_temp" >
			<h3>Temperature</h3>
			<% if !@temperatures.empty? %>
				<table class="table table-striped table-bordered table-hover"> 
					<tr>
					    <th>Time</th>
					    <th>Value</th>
					    <th>Error</th>
					</tr>

				<% @temperatures.each do |temperature| %>
				  <tr>
				    <td><%= temperature.time %></td>
				    <td><%= temperature.value %></td>
				    <td><%= temperature.error %></td>
				  </tr>
				<% end %>
				</table>
			<% else %>
				No temperatures were recorded in this experiment.
			<% end %>
		</div>

		<div id="raw_ph">
			<h3>pH</h3>
			<% if !@pHs.empty? %>
				<table class="table table-striped table-bordered table-hover"> 
					<tr>
					    <th>Time</th>
					    <th>Value</th>
					    <th>Error</th>
					</tr>

				<% @pHs.each do |pH| %>
				  <tr>
				    <td><%= pH.time %></td>
				    <td><%= pH.value %></td>
				    <td><%= pH.error %></td>
				  </tr>
				<% end %>
				</table>
			<% else %> 
				No pHs were recorded this experiment.
			<% end %>
		</div>
		<div id="raw_do">
			<h3>DO</h3>
			<% if !@dissolvedOxygens.empty? %>
				<table class="table table-striped table-bordered table-hover"> 
					<tr>
					    <th>Time</th>
					    <th>Value</th>
					    <th>Error</th>
					</tr>

				<% @dissolvedOxygens.each do |oxygen| %>
				  <tr>
				    <td><%= oxygen.time %></td>
				    <td><%= oxygen.value %></td>
				    <td><%= oxygen.error %></td>
				  </tr>
				<% end %>
				</table>
			<% else %> 
				No DO readings were recorded this experiment. 
			<% end %>
		</div>
		<div id="raw_agit">
			<h3>Agitations</h3>
			<% if !@agitations.empty? %>
				<table class="table table-striped table-bordered table-hover"> 
					<tr>
					    <th>Time</th>
					    <th>Value</th>
					    <th>Error</th>
					</tr>

				<% @agitations.each do |agitation| %>
				  <tr>
				    <td><%= agitation.time %></td>
				    <td><%= agitation.value %></td>
				    <td><%= agitation.error %></td>
				  </tr>
				<% end %>
				</table>
			<% else %> 
				No agitation readings were recorded this experiment. 
			<% end %> 
		</div>
	</div>
</div>
<script>
var shiftWindow = function() { scrollBy(0, -50) };
if (location.hash) shiftWindow();
window.addEventListener("hashchange", shiftWindow);
</script>
<%= link_to 'Back', experiments_path %>

app/views/experiments/raw_data.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Datapoint</Data></Cell>
        <Cell><Data ss:Type="String">Time (s)</Data></Cell>
        <Cell><Data ss:Type="String">Temperature</Data></Cell>
        <Cell><Data ss:Type="String">pH</Data></Cell>
        <Cell><Data ss:Type="String">Agitation</Data></Cell>
        <Cell><Data ss:Type="String">d0</Data></Cell>
      </Row>
    <% (@minimumGroupInt..@maximumGroupInt).each do |line| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= line %></Data></Cell>
        <Cell><Data ss:Type="String"><%= if !@temperatures.last.nil? then @temperatures.last.time end %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= if @temperatures and !@temperatures.empty? and @temperatures.last.group_int == line then @temperatures.pop.value end  %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= if @pHs and !@pHs.empty? and @pHs.last.group_int == line then @pHs.pop.value end %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= if @agitations and !@agitations.empty? and @agitations.last.group_int == line then @agitations.pop.value end %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= if @dissolvedOxygens and !@dissolvedOxygens.empty? and @dissolvedOxygens.last.group_int == line then @dissolvedOxygens.pop.value end %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/experiments/show.html.erb
<%= javascript_include_tag "experiments" %>

<p id="notice"><%= notice %></p>
<%= button_to "Raw Data", raw_data_path(@experiment) %>
<%= button_to "Excel", raw_data_path(@experiment, format: "xls")%> 
<style>

#tempChart svg {
  height: 200px;
}
#agitChart svg {
  height: 200px;
}
#pHChart svg {
  height: 200px;
}
#doChart svg {
  height: 200px;
}


</style>

<h3>Temperature</h3>
<div id="tempChart">
  <svg></svg>
</div>
<h3>pH</h3>
<div id="pHChart">
  <svg></svg>
</div>
<h3>Agitation</h3>
<div id="agitChart">
  <svg></svg>
</div>
<h3>Dissolved Oxygen</h3>
<div id="doChart">
  <svg></svg>
</div>

<!-- 

<% if !@temperatures.empty? %>
	<h3>Temperature</h3>
	<table class="table table-striped table-bordered table-hover"> 
		<tr>
		    <th>Time</th>
		    <th>Value</th>
		    <th>Error</th>
		</tr>

	<% @temperatures.each do |temperature| %>
	  <tr>
	    <td><%= temperature.time %></td>
	    <td><%= temperature.value %></td>
	    <td><%= temperature.error %></td>
	  </tr>
	<% end %>
	</table>
<% end %>

<% if !@pHs.empty? %>
	<h3>pH</h3>
	<table class="table table-striped table-bordered table-hover"> 
		<tr>
		    <th>Time</th>
		    <th>Value</th>
		    <th>Error</th>
		</tr>

	<% @pHs.each do |pH| %>
	  <tr>
	    <td><%= pH.time %></td>
	    <td><%= pH.value %></td>
	    <td><%= pH.error %></td>
	  </tr>
	<% end %>
	</table>
<% end %>

<% if !@dissolvedOxygens.empty? %>
	<h3>DO</h3>
	<table class="table table-striped table-bordered table-hover"> 
		<tr>
		    <th>Time</th>
		    <th>Value</th>
		    <th>Error</th>
		</tr>

	<% @dissolvedOxygens.each do |oxygen| %>
	  <tr>
	    <td><%= oxygen.time %></td>
	    <td><%= oxygen.value %></td>
	    <td><%= oxygen.error %></td>
	  </tr>
	<% end %>
	</table>
<% end %>

<% if !@agitations.empty? %>
	<h3>Agitations</h3>
	<table class="table table-striped table-bordered table-hover"> 
		<tr>
		    <th>Time</th>
		    <th>Value</th>
		    <th>Error</th>
		</tr>

	<% @agitations.each do |agitation| %>
	  <tr>
	    <td><%= agitation.time %></td>
	    <td><%= agitation.value %></td>
	    <td><%= agitation.error %></td>
	  </tr>
	<% end %>
	</table>
<% end %> -->

<%= link_to 'Back', experiments_path %>

app/views/home/index.html.erb
<h1>Bioduino Project</h1>
<%=link_to experiments_path do %><h3> List of all Experiments</h3><% end %>
<%= link_to "/current" do %><h5>Most recent experiment</h5><% end %>

Contact Earl St Sauver (estsauver@gmail.com) with any questions 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Bioduino", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bioduino" %></title>
        <%= include_gon %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bioduino" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %> 
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>